### ISSUE TITLE
Avoidance obstacles

### ISSUE THREAD

**Issue by FabianBell** [tum-phoenix/phx-flight-ros-golden-snitch#1]
# Details
* make decisions for new path to avoid obstacles
* ROS Input-Output Details
  * Input: Distance to human, direction of human (x,y in image frame), ranges from the range sensors.
  * Output: python array [vx, vy, vz, yaw] Velocities in the direction to move in the next 

# Tasks
- [x] detecting cases
- [x] solutions for cases
- [x] implement solution with sensor information 
- [x] Testing
- [x] Basic documentation of the cases and the solution

# Criteria 
* avoids walls in 2D when sensors send signal
* escape from human if human_info sends warning

**Comment by carolineRe13** [comment]
Hey!

**Comment by KonstantinIkonomou** [comment]
hello there

**Comment by FabianBell** [comment]
@carolineRe13 
I have made some changes to the style of the code. I left a note file which contains some remarks you should consider for further development.

**Comment by FabianBell** [comment]
I will continue the work after the meeting with @carolineRe13.

**Comment by hflemmen** [comment]
A little unclear, but did you have a meeting? If so, would you perhaps include a summary here?

**Comment by FabianBell** [comment]
No we are about to find a date for the meeting.

**Comment by FabianBell** [comment]
# Meeting mit @carolineRe13 
## Open questions for @hflemmen :
1. Which parameters does the script receives 
 * range sensors? -> which format? which order of the sensors? Threshold?
 * human info? -> currently: distance, horizontal  angle and vertical angle
2. when flying back -> still try to center the human?
 * we might lose the human when accelerating backwards

**Comment by hflemmen** [comment]
1. The ranges are a python array of floats. They are in the same order as
the the sensors at the cage. I.e. the index corresponds to the index on the
individual sensors. (Possibly -1 if they are 1 indexed). I suggested for
Caroline to make an array of length 8 containing the directions of the
individual sensors. We will have to get the actual directions from the CAD
model or the actual drone. The values are meters and the maximum range is
2m.

Seems you got the human info correct.

2. I would suggest to center the human also when retreating. We have
nothing better to use the camera for. I think we accept the risk of loosing
track.




ons. 22. apr. 2020, 15.54 skrev FabianBell <notifications@github.com>:

**Comment by FabianBell** [comment]
# Results from Meeting with @hflemmen 
1. Sensor ordering is not sure -> general config file (yaml)
  => two general config file -> physical + software parameters
2. Range sensor type => https://github.com/Terabee/teraranger_array/blob/master/msg/RangeArray.msg 
3. When flying back still center human 
4. ignore vertical offset/angel of human
5. search human by rotating -> start with direction we lost human

**Comment by FabianBell** [comment]
I have updated the decision tree. I am not ready yet. I will write a dokumentation tomorrow. Good night :)

**Comment by FabianBell** [comment]
I wrote the test cases and all passed. I couldn't try it with ros since it is not released for ubuntu 20.04.

**Comment by FabianBell** [comment]
# Done
I have extended the [documentation](https://github.com/tum-phoenix/phx-flight-ros-golden-snitch/wiki/Decision-Tree) and described the solution.

**Comment by hflemmen** [comment]
> I wrote the test cases and all passed. I couldn't try it with ros since it is not released for ubuntu 20.04.

I tried it with ros(`catkin run_tests`) too, and it passed.
