### ISSUE TITLE
Local mapping with range sensors and optical flow

### ISSUE THREAD

**Issue by hflemmen** [tum-phoenix/phx-flight-ros-golden-snitch#12]
# Details

## Input

- Range sensor readings
- Odometry data (Relative movement data)

## Output

- Sparse pointcloud of the last `n` range sensor readings in the "room frame".

We can try to use the relative pose between the different range sensor readings to align them in the same frame. I.e. the successive range sensor readings of the same wall should end up on a line. Then it might be that we can use this (very) spare point cloud in the next generation decision maker. The odometry estimate from the optical flow sensor will drift over time, invalidate old mapped features, but we can just discard them. This will give us a less extensive map, but maybe it can be helpful nevertheless. 

# Tasks

- [ ] Read the relative pose from `mavros`.
- [ ] Read the range sensor values
- [ ] Decide for a feasible datastructure for the map
- [ ] Implement mapping
- [ ] Publish a ros pointclout to a suitable topic. (And view the visualsation in `rviz`)
- [ ] Write tests

# Criteria

- A node that publishes a local map of the drone

**Comment by adrisor23** [comment]
Can someone assign me to this issue?

**Comment by hflemmen** [comment]
I now made the node interface in 3f4b8da. I tested briefly if it works to publish point clouds to rviz, and it does. I have not tested the range sensors. I believe I have found the correct mavros topic for the position, but if not can we change it later.

**Comment by adrisor23** [comment]
I have mostly implemented the mapping function and the "sensor value age tracker" also, but still have to enable deleting the oldest values.
