### ISSUE TITLE
Run Model without TPU

### ISSUE THREAD

**Issue by FabianBell** [tum-phoenix/phx-flight-ros-golden-snitch#2]
# Details
* make the human prediction runnable without the TPU
* the current model uses a compiled TPU model 
* the alternative model does not provide python code

# Tasks
- [x] include a new model that runs with tensorflow lite
- [x] get new predictions
- [ ] calculate the pixle values and scores of the predictions
- [ ] include the new keypoints in the human_info script  

# Criteria 
* the prediction runs without the coral (meight be slower)
* the prediction is simmilar (close) to the old predictions

**Comment by FabianBell** [comment]
I updated the script based on the description [here](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5). The predictions are still wrong but look better. It meight be that they are just scaled or rotated. I am going to check that.

**Comment by FabianBell** [comment]
I tried the [description](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5) but it is still not working. I will search for alternative models or descriptions.

**Comment by FabianBell** [comment]
I found a python framework of [posente](https://github.com/rwightman/posenet-python) but it uses deprecated software. This meight be our worst case alternative.

**Comment by FabianBell** [comment]
All other descriptions I found did it the same way I did. The python framework for posenet is not working with all the tensorflow versions I tried. I am going to discuss that at the next meeting.

I have tried to generate the data on google colab with a tpu but the api requires an edge tpu to be connected.

**Comment by FabianBell** [comment]
I tried https://github.com/eldar/pose-tensorflow. I wa easy to use but made realy bad predictions.
![Figure_1](https://user-images.githubusercontent.com/33394443/79228070-27a0d280-7e61-11ea-8082-e37abf3e4be8.png)

**Comment by FabianBell** [comment]
# Done
I am going to stop working in this issue because it is not worth the effort.
