### ISSUE TITLE
Attitude correction in wall ranges

### ISSUE THREAD

**Issue by hflemmen** [tum-phoenix/phx-flight-ros-golden-snitch#5]
# Details
The range sensors will tilt when the drone moves so the distances to the walls will will we overestimated. Since we can get the attitude from ardupilot, we can correct it. If we also combine the altitude, we can reason if we are detecting the floor instead of the walls.
Input: Teraranges ranges, Attutude from IMU, relative altitude from the downfacing range sensor(already attitude corrected).
Output: Ranges, corrected for inclination. Perhaps a mask indicating if the floor is detected.

# Tasks

- [x] Make the node
- [x] Make the interface to ros
- [x] Make the correction logic
- [x] Test everything

# Criteria
* Outputs correct distances independent of drone inclination.

**Comment by hflemmen** [comment]
This now tested, both with unittests and a simple integration test. It is not tested in flight, but we close it now anyway.

**Comment by hflemmen** [comment]
This now tested, both with unittests and a simple integration test. It is not tested in flight, but we close it now anyway.
